# Conda environment for Slide Analysis Agent
# -----------------------------------------
# Usage:
#   conda env create -f environment.yml
#   conda activate slide-analysis-agent
# -----------------------------------------
name: slide-analysis-agent
channels:
  - conda-forge
  - defaults
dependencies:
  # Core
  - python >=3.9,<3.13
  - pip
  - pillow >=10.0
  - tqdm >=4.66
  - pdf2image
  - pypdf2
  # OpenAI / lang-related via pip (latest versions often faster via PyPI)
  - pip:
      - langgraph>=0.0.21
      - python-pptx>=0.6.23
      - openai>=1.3.0
      - pydantic>=1.10.0
      # Dev optional
      - black>=23.7.0
      - isort>=5.12.0
      - flake8>=6.1.0
